Updated onu-deb

diff --git a/nza-userland/components/illumos/src/onbld/onu-deb b/nza-userland/components/illumos/src/onbld/onu-deb
--- a/nza-userland/components/illumos/src/onbld/onu-deb
+++ b/nza-userland/components/illumos/src/onbld/onu-deb
@@ -1,214 +1,89 @@
 #!/bin/bash
-
-# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
-
-# VERSION 1.1
+#
+# CDDL HEADER START
+#
+# The contents of this file are subject to the terms of the
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
+#
+# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
+# or http://www.opensolaris.org/os/licensing.
+# See the License for the specific language governing permissions
+# and limitations under the License.
+#
+# When distributing Covered Code, include this CDDL HEADER in each
+# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
+# If applicable, add the following below this CDDL HEADER, with the
+# fields enclosed by brackets "[]" replaced with your own identifying
+# information: Portions Copyright [yyyy] [name of copyright owner]
+#
+# CDDL HEADER END
+#
+# Copyright 2013 Nexenta Systems, Inc. All rights reserved.
+#
+# Version 2.0
 
 #set -x
 
 PATH=/usr/gnu/bin:/usr/bin:/usr/sbin
 export PATH
 
-VERBOSE=0
-NO_ZONES=0
+CONSOLE=0
 REPODIR=""
 TARGETBE=""
-UPGRADE=0
+TARGETMOUNT=""
 
 TMPDIR="/tmp/apt.$$"
+LOG="/root/upgrade.log.$$"
 
 BEADM="/usr/sbin/beadm"
 MKDIR="/usr/bin/mkdir"
 BOOTADM="/usr/sbin/bootadm"
-CHROOT="/usr/gnu/bin/chroot"
-MOUNT="/usr/sbin/mount"
-UMOUNT="/usr/sbin/umount"
-
-LOG="/root/upgrade.log.$$"
-
-CHROOTENV="env -i \
-PATH=/usr/gnu/bin:/usr/bin:/sbin:/usr/sbin \
-DEBCHROOT=1 \
-LOGNAME=root \
-HOME=/root \
-USER=root \
-TERM=xterm"
-
-TMOUNTED=0
+ECHO="/usr/bin/echo"
+CAT="/usr/bin/cat"
+CP="/usr/bin/cp"
+MV="/usr/bin/mv"
+APTGET="/usr/bin/apt-get"
 
 function usage()
 {
-	echo "Usage:"
-	echo "	$0 -t <BE name> -d <path to local APT>"
-	echo ""
-	echo "Example:"
-	echo "	$0 -t nightly-`date +%Y-%m-%d` -d \$PWD/packages/i386/apt"
+	${ECHO} "Usage:"
+	${ECHO} "	$0 -t <BE name> -d <path to local APT>"
+	${ECHO}
+	${ECHO} "Example:"
+	${ECHO} "	$0 -t nightly-`date +%Y-%m-%d` -d \$PWD/packages/i386/apt"
 	exit 0
 }
 
-function exit_error()
-{
-	echo "$*" 2>&1 | tee -a $LOG
-	exit 2
-}
-
-function do_cmd()
-{
-	[ $VERBOSE -gt 0 ] && echo "$*" 2>&1 | tee -a $LOG
-	eval "$*"
-	exit_code=$?
-	[ $exit_code -eq 0 ] && return
-	[ $TMOUNTED -eq 1 ] && tumount
-	exit_error "'$*'" failed: exit code $exit_code
-}
-
-function get_mountpoint()
-{
-	local MNTPOINT=`zfs get -H mountpoint $1 | nawk '{print \$3}'`
-	echo $MNTPOINT
-}
-
-function is_root_zpool()
-{
-	local ZROOT=0
-	BOOTFS=`zpool get bootfs $1 | grep bootfs | nawk '{print \$3}'`
-	if [ "$BOOTFS" = "-" ]; then
-	    ZROOT=0
+logcmd() {
+	if [[ -z "$CONSOLE" ]]; then
+		${ECHO} CMD: "$@" >> $LOG
+		"$@" >> $LOG 2>&1
 	else
-	    ZROOT=1
+		${ECHO} CMD: "$@" | tee $LOG
+		"$@" | tee $LOG 2>&1
 	fi
-	echo $ZROOT
 }
 
-function mount_rec()
-{
-	local MDIR=""
-	local MPATH=""
-	local CNT=2
-	local LMNTS=`echo $1 | nawk -F'/' '{print NF}'`
-
-	(( LMNTS++ ))
-	while [ $CNT -lt $LMNTS ]
-	do
-	    MDIR=`echo $1 | cut -d'/' -f$CNT`
-	    MPATH="$MPATH/$MDIR"
-	    (( CNT++ ))
-	    $MOUNT -F lofs -O $MPATH $TMPDIR/$MPATH
-	done
+logmsg() {
+	${ECHO} "$@" >> $LOG
+	${ECHO} "$@"
 }
 
-function umount_rec()
-{
-	local REPODIRTEMP="$1"
-
-	while [ "$REPODIRTEMP" != "/" ]
-	do
-	    $UMOUNT $TMPDIR/$REPODIRTEMP
-	    REPODIRTEMP=`dirname $REPODIRTEMP`
-	done
+logerr() {
+	logmsg $@
+	fullabort
 }
 
-
-function mount_dataset()
-{
-	local ZMNTS=`zfs list -H | nawk '{print \$5}'`
-	local REPODIRTEMP="$REPODIR"
-
-	while [ "$REPODIRTEMP" != "/" ]
-	do
-	    for ZMNT in $ZMNTS
-	    do
-		if [ "$REPODIRTEMP" = "$ZMNT" ]; then
-		    mount_rec $ZMNT
-		    return
-		fi
-	    done
-	    REPODIRTEMP=`dirname $REPODIRTEMP`
-	done
+fullabort() {
+	printf "\nAborting. See $LOG for details\n"
+	exit 1
 }
 
-function umount_dataset()
-{
-	local ZMNTS=`zfs list -H | nawk '{print \$5}'`
-	local REPODIRTEMP="$REPODIR"
-
-	while [ "$REPODIRTEMP" != "/" ]
-	do
-	    for ZMNT in $ZMNTS
-	    do
-		if [ "$REPODIRTEMP" = "$ZMNT" ]; then
-		    umount_rec $ZMNT
-		    return
-		fi
-	    done
-	    REPODIRTEMP=`dirname $REPODIRTEMP`
-	done
-}
-
-function tmount ()
-{
-	local TMPDIR="$1"
-	$CHROOT $TMPDIR $MOUNT /proc
-	$MOUNT -F lofs -O /tmp $TMPDIR/tmp
-	$MOUNT -F lofs -O /devices $TMPDIR/devices
-	$MOUNT -F lofs -O /dev $TMPDIR/dev
-	$MOUNT -F lofs -O /etc/mnttab $TMPDIR/etc/mnttab
-if [ ! -z "$REPODIR" ]; then
-	mount_dataset
-fi
-	TMOUNTED=1
-}
-
-function tumount ()
-{
-	local TMPDIR="$1"
-if [ ! -z "$REPODIR" ]; then
-	umount_dataset
-fi
-	$UMOUNT $TMPDIR/etc/mnttab
-	$UMOUNT $TMPDIR/dev
-	$UMOUNT $TMPDIR/devices
-	$UMOUNT $TMPDIR/tmp
-	$CHROOT $TMPDIR $UMOUNT /proc 2> /dev/null 1>&2
-	TMOUNTED=0
-}
-
-function get_clones_dev ()
-{
-	local TMP="$1"
-	local CLONEPKGS=""
-	DEVPKGS=`ls $TMP/var/lib/dpkg/info/*.postinst`
-
-	for DEVPKG in $DEVPKGS
-	do
-	    CLONE=`cat $DEVPKG | grep update_drv | grep clone | wc -l`
-	    if (( $CLONE > 0 )); then
-		DEVPKG=`basename $DEVPKG | sed -e 's/\..*$//'`
-		CLONEPKGS="$CLONEPKGS $DEVPKG"
-	    fi
-	done
-	echo $CLONEPKGS
-}
-
-function rm_package_name ()
-{
-	local RPKG="$1"
-	shift
-	local RPKGS="$*"
-	local ROUT=""
-
-	for p in $RPKGS
-	do
-	    if [ "$p" != "$RPKG" ]; then
-		ROUT="$ROUT $p"
-	    fi
-	done
-	echo $ROUT
-}
 
 ###### main ######
 
-while getopts :d:t:UvZ i ; do
+while getopts :d:t:R:v i ; do
 	case $i in
 	d)
 		REPODIR="$OPTARG"
@@ -216,14 +91,11 @@ while getopts :d:t:UvZ i ; do
 	t)
 		TARGETBE="$OPTARG"
 		;;
-	U)
-		UPGRADE=1
+	R)
+		TARGETMOUNT="$OPTARG"
 		;;
 	v)
-		VERBOSE=1
-		;;
-	Z)
-		NO_ZONES=1
+		CONCOLE=1
 		;;
 	*)
 		usage
@@ -232,83 +104,75 @@ done
 shift `expr $OPTIND - 1`
 
 [ -n "$1" ] && usage
-[ -z "$TARGETBE" ] && usage
-[ -z "$REPODIR" -a $UPGRADE -lt 1 ] && usage
+[ -z "$TARGETBE" -a -z "$TARGETMOUNT" ] && usage
+[ -z "$REPODIR" ] && usage
+
 if [ $UPGRADE -lt 1 -a ! -f "$REPODIR/conf/distributions" ]; then
-    echo "Error: Local APT unavailable, please check your path to repo dir: '$REPODIR'"
-    exit 1
+	logmsg "Local APT unavailable, please check your path to repo dir: '$REPODIR'"
+	fullabort
 fi
 
-do_cmd mkdir -p "$TMPDIR" 2>&1 | tee -a $LOG
-do_cmd beadm create "$TARGETBE" 2>&1 | tee -a $LOG
-do_cmd beadm mount "$TARGETBE" "$TMPDIR" 2>&1 | tee -a $LOG
+${ECHO} "$(basename $0) started at `date`" > $LOG
 
-if [ ! -z "$REPODIR" ]; then
-    do_cmd mv /etc/apt/sources.list /etc/apt/sources.list.saved
-    echo "deb file://$REPODIR unstable main" > /etc/apt/sources.list
-    do_cmd cp -f /etc/apt/sources.list $TMPDIR/etc/apt/sources.list
+if [ -z "$TARGETMOUNT" ]; then
+	logcmd ${MKDIR} -p "$TMPDIR"
+	logcmd ${BEADM} create "$TARGETBE"
+	logcmd ${BEADM} mount "$TARGETBE" "$TMPDIR"
+else
+	TMPDIR="$TARGETMOUNT"
 fi
 
-KERNEL_YES=0
-
-do_cmd apt-get -o=dir::cache=$TMPDIR/var/cache/apt clean 2>&1 | tee $LOG
-
-do_cmd apt-get -o=dir::cache=$TMPDIR/var/cache/apt update 2>&1 | tee -a $LOG
-
-do_cmd apt-get -o=dir::cache=$TMPDIR/var/cache/apt -d -f -y --force-yes upgrade 2>&1 | tee -a $LOG
-
-DEBPKGS=`apt-get -o=dir::cache=$TMPDIR/var/cache/apt -s -u upgrade | grep Inst | nawk '{print $2}'`
-
-# check system-kernel
-for DEBPKG in $DEBPKGS
-do
-    if [ "x$DEBPKG" = "xsystem-kernel" ]; then
-	KERNEL_YES=1
-    fi
-done
-
-if [ "$KERNEL_YES" = "1" ]; then
-    CLONEPKGS=`get_clones_dev $TMPDIR`
-    CLONEPKGS=`rm_package_name "system-kernel" "$CLONEPKGS"`
-    for CLONPKG in $CLONEPKGS
-    do
-	DEBPKGS=`rm_package_name "$CLONPKG" "$DEBPKGS"`
-    done
-    DEBPKGS=`rm_package_name "system-kernel" "$DEBPKGS"`
-    DEBPKGS="system-kernel $CLONEPKGS $DEBPKGS"
+if [ ! -z "$REPODIR" -a -z "$TARGETMOUNT" ]; then
+	logcmd ${MV} /etc/apt/sources.list /etc/apt/sources.list.saved
+	${ECHO} "deb file://$REPODIR nza-kernel main" > /etc/apt/sources.list
+	logcmd ${CP} -f /etc/apt/sources.list $TMPDIR/etc/apt/sources.list
 fi
 
-do_cmd tmount $TMPDIR
+export APT_CLONE_ENV=1
 
-do_cmd $CHROOT $TMPDIR $CHROOTENV apt-get update 2>&1 | tee -a $LOG
+logcmd ${APTGET} -R $TMPDIR update
+logcmd ${APTGET} -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -R $TMPDIR install -y --force-yes sunwcsd
+logcmd ${APTGET} -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -R $TMPDIR install -y --force-yes sunwcs
+logcmd ${APTGET} -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -R $TMPDIR install -y --force-yes system-kernel
+logcmd ${APTGET} -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -R $TMPDIR dist-upgrade -y --force-yes
 
-do_cmd $CHROOT $TMPDIR $CHROOTENV apt-get upgrade -y --force-yes 2>&1 | tee -a $LOG
-
-do_cmd $CHROOT $TMPDIR $CHROOTENV apt-get install -f -y --force-yes 2>&1 | tee -a $LOG
-
-do_cmd tumount $TMPDIR
-
-for DEBPKG in $DEBPKGS
-do
-    echo "Configuring: $DEBPKG ... " 2>&1 | tee -a $LOG
-    [ -f $TMPDIR/var/lib/dpkg/info/$DEBPKG.prerm ] && ( BASEDIR="$TMPDIR" $TMPDIR/var/lib/dpkg/info/$DEBPKG.prerm upgrade 2>&1 | tee -a $LOG )
-    [ -f $TMPDIR/var/lib/dpkg/info/$DEBPKG.postinst ] && ( DEBUPGRADE=1 BASEDIR="$TMPDIR" $TMPDIR/var/lib/dpkg/info/$DEBPKG.postinst configure 2>&1 | tee -a $LOG )
-done
-
-do_cmd touch $TMPDIR/reconfigure
-
-do_cmd $BOOTADM update-archive -R $TMPDIR 2>&1 | tee -a $LOG
-
-if [ ! -z "$REPODIR" ]; then
-    do_cmd mv /etc/apt/sources.list.saved /etc/apt/sources.list
-    do_cmd cp -f /etc/apt/sources.list $TMPDIR/etc/apt/sources.list
+if [ -z "$TARGETMOUNT" ]; then
+	logcmd $BOOTADM update-archive -R $TMPDIR
 fi
 
-do_cmd beadm umount "$TARGETBE" 2>&1 | tee -a $LOG
+if [ ! -z "$REPODIR" -a -z "$TARGETMOUNT" ]; then
+	logcmd ${MV} /etc/apt/sources.list.saved /etc/apt/sources.list
+	logcmd ${CP} -f /etc/apt/sources.list $TMPDIR/etc/apt/sources.list
+fi
 
-do_cmd beadm activate "$TARGETBE" 2>&1 | tee -a $LOG
+if [ -z "$TARGETMOUNT" ]; then
+	logcmd ${BEADM} umount "$TARGETBE"
+	logcmd ${BEADM} activate "$TARGETBE"
+fi
 
-echo "Upgrade have been done. Please reboot to new dataset '$TARGETBE'." 2>&1 | tee -a $LOG
-echo "You can find log at: '$LOG'." 2>&1 | tee -a $LOG
+${CAT}<<-EOF
+
+                          * * *
+                      SYSTEM NOTICE
+
+     The upgrade has completed successfully:
+       - created new BE '$TARGETBE'
+       - created new GRUB menu entry
+       - upgrade log saved to '$LOG'
+       - the system is ready to reboot into the new BE
+
+   +------------------------------------------------------------------+
+   |                                                                  |
+   |  At this point you have two options:                             |
+   |                                                                  |
+   |   1. You can reboot now, make sure that system is healthy.       |
+   |                                                                  |
+   |   2. Or, you can simply continue using the system as is and      |
+   |      reboot to new BE later.                                    |
+   |                                                                  |
+   +------------------------------------------------------------------+
+EOF
+
+${ECHO} "$(basename $0) finished at `date`" >> $LOG
 
 exit 0
